"use client";

import { useCallback, useEffect, useState } from "react";
import type { ProgramRecord, PromptRecord, SuiteRecord, WorkspaceRecord, WorkspaceTree } from "@agent-console/shared";
import { workspaceApi } from "@/lib/workspacesApi";

const input = "w-full rounded border border-[#252c35] bg-[#101317] px-3 py-2 text-sm text-[#e7ecf2] focus:border-[#3b4654] focus:outline-none";
const button = "rounded border border-[#2a323c] bg-[#181d24] px-3 py-2 text-xs text-[#c3cbd6] hover:bg-[#20262e] disabled:opacity-40";

export function WorkspaceManager({ serverUrl }: { serverUrl: string }) {
  const [items,setItems]=useState<WorkspaceRecord[]>([]); const [tree,setTree]=useState<WorkspaceTree|null>(null);
  const [programId,setProgramId]=useState<number|null>(null); const [suiteId,setSuiteId]=useState<number|null>(null); const [promptId,setPromptId]=useState<number|null>(null);
  const [error,setError]=useState(""); const [busy,setBusy]=useState(false); const [creating,setCreating]=useState(false);
  const [draft,setDraft]=useState({name:"",description:"",workDirectory:""});
  const loadList=useCallback(async(select?:number)=>{ const list=await workspaceApi.list(serverUrl); setItems(list); const id=select ?? tree?.id ?? list[0]?.id; if(id) setTree(await workspaceApi.tree(serverUrl,id)); else setTree(null); },[serverUrl,tree?.id]);
  useEffect(()=>{ void workspaceApi.list(serverUrl).then(async list=>({list,selected:list[0]?.id?await workspaceApi.tree(serverUrl,list[0].id):null})).then(({list,selected})=>{setItems(list);setTree(selected);}).catch(e=>setError(String(e.message))); },[serverUrl]);
  const refresh=async()=>{ if(tree) setTree(await workspaceApi.tree(serverUrl,tree.id)); };
  const act=async(fn:()=>Promise<unknown>,shouldRefresh=true)=>{ setBusy(true);setError("");try{await fn();if(shouldRefresh)await refresh();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);} };
  const choose=async(id:number)=>{setProgramId(null);setSuiteId(null);setPromptId(null);setError("");try{setTree(await workspaceApi.tree(serverUrl,id));}catch(e){setError(e instanceof Error?e.message:String(e));}};
  const program=tree?.programs.find(x=>x.id===programId)??null; const suite=program?.suites.find(x=>x.id===suiteId)??null; const prompt=suite?.prompts.find(x=>x.id===promptId)??null;
  const ask=async(kind:"program"|"suite"|"prompt")=>{const label=window.prompt(`${kind === "prompt" ? "Prompt title" : `${kind} name`}:`);if(!label?.trim())return; if(kind==="program"&&tree) await act(()=>workspaceApi.createChild(serverUrl,"workspaces",tree.id,"programs",{name:label,overview:""})); if(kind==="suite"&&program) await act(()=>workspaceApi.createChild(serverUrl,"programs",program.id,"suites",{name:label,overview:""})); if(kind==="prompt"&&suite) await act(()=>workspaceApi.createChild(serverUrl,"suites",suite.id,"prompts",{title:label,content:"Describe the task here."}));};
  return <div className="flex min-h-0 flex-1 overflow-hidden">
    <aside className="w-64 shrink-0 overflow-y-auto border-r border-[#1d2229] bg-[#0e1115] p-3">
      <div className="mb-3 flex items-center justify-between"><span className="text-xs uppercase tracking-wider text-[#68727f]">Workspaces</span><button className={button} onClick={()=>setCreating(true)}>+ New</button></div>
      <div className="space-y-1">{items.map(w=><button key={w.id} onClick={()=>void choose(w.id)} className={`w-full rounded px-3 py-2 text-left text-sm ${tree?.id===w.id?"bg-[#20262e] text-white":"text-[#9ba5b2] hover:bg-[#161b21]"}`}><div>{w.name}</div><div className="truncate text-[10px] text-[#59626e]">{w.workDirectory}</div></button>)}</div>
    </aside>
    <section className="min-w-0 flex-1 overflow-y-auto p-5">
      {error&&<div className="mb-4 rounded border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-300">{error}</div>}
      {creating&&<form className="mb-5 grid gap-3 rounded border border-[#252c35] bg-[#0e1115] p-4 md:grid-cols-2" onSubmit={e=>{e.preventDefault();void act(async()=>{await workspaceApi.create(serverUrl,draft);setCreating(false);setDraft({name:"",description:"",workDirectory:""});await loadList();});}}><input required className={input} placeholder="Workspace name" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/><input required className={input} placeholder="/absolute/work/directory" value={draft.workDirectory} onChange={e=>setDraft({...draft,workDirectory:e.target.value})}/><textarea className={`${input} md:col-span-2`} placeholder="Description" value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/><div className="flex gap-2"><button disabled={busy} className={button}>Create workspace</button><button type="button" className={button} onClick={()=>setCreating(false)}>Cancel</button></div></form>}
      {!tree?<div className="text-sm text-[#68727f]">Create a workspace to get started.</div>:<>
        <WorkspaceEditor key={`${tree.id}:${tree.updatedAt}`} value={tree} disabled={busy} onSave={v=>act(async()=>{await workspaceApi.update(serverUrl,tree.id,v);await loadList(tree.id);},false)} onDelete={()=>{if(confirm(`Delete “${tree.name}” and all of its programs, suites and prompts?`))void act(async()=>{await workspaceApi.remove(serverUrl,tree.id);setTree(null);await loadList();},false);}}/>
        <div className="mt-5 grid min-h-[420px] grid-cols-1 gap-3 lg:grid-cols-3">
          <Column title="Programs" onAdd={()=>void ask("program")} disabled={busy}>{tree.programs.map(x=><Row key={x.id} active={x.id===programId} label={x.name} onClick={()=>{setProgramId(x.id);setSuiteId(null);setPromptId(null);}}/>)}</Column>
          <Column title="Suites" onAdd={program?()=>void ask("suite"):undefined} disabled={busy}>{program?.suites.map(x=><Row key={x.id} active={x.id===suiteId} label={x.name} onClick={()=>{setSuiteId(x.id);setPromptId(null);}}/>)}</Column>
          <Column title="Prompts" onAdd={suite?()=>void ask("prompt"):undefined} disabled={busy}>{suite?.prompts.map(x=><Row key={x.id} active={x.id===promptId} label={x.title} onClick={()=>setPromptId(x.id)}/>)}</Column>
        </div>
        <div className="mt-4">{prompt?<PromptEditor key={`${prompt.id}:${prompt.updatedAt}`} value={prompt} onSave={v=>act(()=>workspaceApi.updateChild(serverUrl,"prompts",prompt.id,v))} onDelete={()=>void act(()=>workspaceApi.removeChild(serverUrl,"prompts",prompt.id))}/>:suite?<NamedEditor key={`${suite.id}:${suite.updatedAt}`} value={suite} kind="suite" onSave={v=>act(()=>workspaceApi.updateChild(serverUrl,"suites",suite.id,v))} onDelete={()=>void act(()=>workspaceApi.removeChild(serverUrl,"suites",suite.id))}/>:program?<NamedEditor key={`${program.id}:${program.updatedAt}`} value={program} kind="program" onSave={v=>act(()=>workspaceApi.updateChild(serverUrl,"programs",program.id,v))} onDelete={()=>void act(()=>workspaceApi.removeChild(serverUrl,"programs",program.id))}/>:<div className="text-sm text-[#59626e]">Select an item to edit its details.</div>}</div>
      </>}
    </section>
  </div>;
}

function Column({title,onAdd,disabled,children}:{title:string;onAdd?:()=>void;disabled:boolean;children:React.ReactNode}){return <div className="overflow-hidden rounded border border-[#252c35] bg-[#0e1115]"><div className="flex items-center justify-between border-b border-[#252c35] px-3 py-2"><b className="text-xs text-[#9ba5b2]">{title}</b><button disabled={!onAdd||disabled} onClick={onAdd} className="text-xs text-[#72a7d8] disabled:opacity-30">+ Add</button></div><div className="p-2">{children}</div></div>}
function Row({active,label,onClick}:{active:boolean;label:string;onClick:()=>void}){return <button onClick={onClick} className={`mb-1 w-full rounded px-2 py-2 text-left text-sm ${active?"bg-[#26303b] text-white":"text-[#929daa] hover:bg-[#161b21]"}`}>{label}</button>}
function WorkspaceEditor({value,disabled,onSave,onDelete}:{value:WorkspaceTree;disabled:boolean;onSave:(v:unknown)=>void;onDelete:()=>void}){const [v,setV]=useState(value);return <form onSubmit={e=>{e.preventDefault();onSave(v)}} className="grid gap-3 rounded border border-[#252c35] bg-[#0e1115] p-4 md:grid-cols-2"><input className={input} value={v.name} onChange={e=>setV({...v,name:e.target.value})}/><input className={input} value={v.workDirectory} onChange={e=>setV({...v,workDirectory:e.target.value})}/><textarea className={`${input} md:col-span-2`} value={v.description} onChange={e=>setV({...v,description:e.target.value})}/><div className="flex gap-2"><button disabled={disabled} className={button}>Save workspace</button><button type="button" onClick={onDelete} className="text-xs text-red-300">Delete workspace</button></div></form>}
function NamedEditor({value,kind,onSave,onDelete}:{value:ProgramRecord|SuiteRecord;kind:string;onSave:(v:unknown)=>void;onDelete:()=>void}){const [v,setV]=useState({name:value.name,overview:value.overview});return <form onSubmit={e=>{e.preventDefault();onSave(v)}} className="space-y-3 rounded border border-[#252c35] bg-[#0e1115] p-4"><input className={input} value={v.name} onChange={e=>setV({...v,name:e.target.value})}/><textarea rows={4} className={input} value={v.overview} onChange={e=>setV({...v,overview:e.target.value})}/><div className="flex gap-3"><button className={button}>Save {kind}</button><button type="button" onClick={()=>confirm(`Delete this ${kind} and everything inside it?`)&&onDelete()} className="text-xs text-red-300">Delete</button></div></form>}
function PromptEditor({value,onSave,onDelete}:{value:PromptRecord;onSave:(v:unknown)=>void;onDelete:()=>void}){const [v,setV]=useState({title:value.title,content:value.content});return <form onSubmit={e=>{e.preventDefault();onSave(v)}} className="space-y-3 rounded border border-[#252c35] bg-[#0e1115] p-4"><input className={input} value={v.title} onChange={e=>setV({...v,title:e.target.value})}/><textarea rows={10} className={`${input} font-mono`} value={v.content} onChange={e=>setV({...v,content:e.target.value})}/><div className="flex gap-3"><button className={button}>Save prompt</button><button type="button" onClick={()=>confirm("Delete this prompt?")&&onDelete()} className="text-xs text-red-300">Delete</button></div></form>}
