import assert from "node:assert/strict";
import { existsSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import test from "node:test";
import { webSourceHash } from "./env/webBuild.ts";
import { repoRoot } from "./realState.ts";

test("webSourceHash ignores files generated by Next and TypeScript builds", () => {
  const generated = [
    join(repoRoot, "web", "next-env.d.ts"),
    join(repoRoot, "web", "tsconfig.tsbuildinfo"),
  ];
  const originals = generated.map(path => existsSync(path) ? readFileSync(path) : null);
  const before = webSourceHash("http://127.0.0.1:4120");

  try {
    generated.forEach((path, index) => writeFileSync(path, `generated-${index}-${Date.now()}\n`));
    assert.equal(webSourceHash("http://127.0.0.1:4120"), before);
  } finally {
    generated.forEach((path, index) => {
      const original = originals[index]!;
      if (original === null) rmSync(path, { force: true });
      else writeFileSync(path, original);
    });
  }
});
